local OrionLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/shlexware/Orion/main/source"))()
local Window = OrionLib:MakeWindow({Name="Test UI", IntroText="Orion Works!"})
local Tab = Window:MakeTab({Name="Main"})
Tab:AddButton({Name="Click Me", Callback=function() OrionLib:MakeNotification({Name="Test", Content="UI Muncul!", Time=3}) end})
OrionLib:Init()
